export interface Question {
  id: string
  text: string
  type: 'single' | 'multiple' | 'yesno' | 'text'
  options?: string[]
  field: string
  roleFilter?: Record<string, string[]>
}

export interface Area {
  id: string
  name: string
  description: string
  icon: string
  questions: Question[]
}

export const areas: Area[] = [
  {
    id: 'tecnologia',
    name: 'Tecnología / IT',
    description: 'Desarrollo de software, infraestructura, datos, ciberseguridad',
    icon: '💻',
    questions: [
      { id: 'tech_role', text: '¿Cuál es tu rol principal?', type: 'single', options: ['Frontend', 'Backend', 'Full Stack', 'DevOps / SRE', 'Data Science / ML', 'Mobile', 'QA / Testing', 'Ciberseguridad', 'Product Manager', 'UX / UI', 'SysAdmin / Infra', 'Arquitecto de Software', 'Otro'], field: 'title' },
      { id: 'tech_years', text: '¿Cuántos años de experiencia profesional tienes?', type: 'single', options: ['0 años / Sin experiencia', 'Menos de 1 año', '1-2 años', '3-5 años', '6-10 años', 'Más de 10 años'], field: 'experience' },
      { id: 'tech_langs', text: '¿Qué lenguajes de programación manejas?', type: 'multiple', options: ['JavaScript/TypeScript', 'Python', 'Java', 'C#', 'Go', 'Rust', 'C/C++', 'Ruby', 'PHP', 'Swift', 'Kotlin', 'SQL', 'Otro'], field: 'skills',
        roleFilter: {
          'Frontend': ['JavaScript/TypeScript'],
          'Backend': ['JavaScript/TypeScript', 'Python', 'Java', 'C#', 'Go', 'Rust', 'C/C++', 'Ruby', 'PHP', 'SQL'],
          'Full Stack': ['JavaScript/TypeScript', 'Python', 'Java', 'C#', 'Go', 'Rust', 'C/C++', 'Ruby', 'PHP', 'SQL'],
          'DevOps / SRE': ['Python', 'Go', 'Ruby', 'SQL'],
          'Data Science / ML': ['Python', 'SQL'],
          'Mobile': ['JavaScript/TypeScript', 'Java', 'Kotlin', 'Swift', 'C#', 'C/C++'],
          'QA / Testing': ['JavaScript/TypeScript', 'Python', 'Java', 'C#', 'SQL'],
          'Ciberseguridad': ['JavaScript/TypeScript', 'Python', 'Go', 'C/C++', 'Ruby', 'SQL'],
          'SysAdmin / Infra': ['Python', 'Go', 'Ruby', 'SQL'],
          'Arquitecto de Software': ['JavaScript/TypeScript', 'Python', 'Java', 'C#', 'Go', 'SQL'],
          'Product Manager': [],
          'UX / UI': ['JavaScript/TypeScript'],
          'Otro': ['JavaScript/TypeScript', 'Python', 'Java', 'C#', 'Go', 'Rust', 'C/C++', 'Ruby', 'PHP', 'Swift', 'Kotlin', 'SQL', 'Otro'],
        },
      },
      { id: 'tech_frameworks', text: '¿Qué frameworks o librerías usas?', type: 'multiple', options: ['React', 'Vue', 'Angular', 'Next.js', 'Node.js / Express', 'Django / Flask', 'Spring Boot', 'ASP.NET', 'FastAPI', 'TensorFlow / PyTorch', 'Docker / Kubernetes', 'AWS / GCP / Azure', 'Otro'], field: 'skills',
        roleFilter: {
          'Frontend': ['React', 'Vue', 'Angular', 'Next.js'],
          'Backend': ['Node.js / Express', 'Django / Flask', 'Spring Boot', 'ASP.NET', 'FastAPI', 'Docker / Kubernetes', 'AWS / GCP / Azure'],
          'Full Stack': ['React', 'Vue', 'Angular', 'Next.js', 'Node.js / Express', 'Django / Flask', 'Spring Boot', 'FastAPI', 'Docker / Kubernetes', 'AWS / GCP / Azure'],
          'DevOps / SRE': ['Docker / Kubernetes', 'AWS / GCP / Azure'],
          'Data Science / ML': ['TensorFlow / PyTorch', 'FastAPI', 'Docker / Kubernetes', 'AWS / GCP / Azure'],
          'Mobile': ['React', 'Node.js / Express', 'Docker / Kubernetes', 'AWS / GCP / Azure'],
          'QA / Testing': ['Node.js / Express', 'Docker / Kubernetes', 'AWS / GCP / Azure'],
          'Ciberseguridad': ['Docker / Kubernetes', 'AWS / GCP / Azure'],
          'SysAdmin / Infra': ['Docker / Kubernetes', 'AWS / GCP / Azure'],
          'Arquitecto de Software': ['React', 'Vue', 'Angular', 'Next.js', 'Node.js / Express', 'Django / Flask', 'Spring Boot', 'FastAPI', 'Docker / Kubernetes', 'AWS / GCP / Azure'],
          'Product Manager': [],
          'UX / UI': [],
          'Otro': ['React', 'Vue', 'Angular', 'Next.js', 'Node.js / Express', 'Django / Flask', 'Spring Boot', 'ASP.NET', 'FastAPI', 'TensorFlow / PyTorch', 'Docker / Kubernetes', 'AWS / GCP / Azure', 'Otro'],
        },
      },
      { id: 'tech_education', text: '¿Cuál es tu nivel de educación formal?', type: 'single', options: ['Secundaria / Bachillerato', 'Técnico / Tecnólogo', 'Universidad (pregrado)', 'Postgrado / Maestría', 'Doctorado / PhD'], field: 'education' },
      { id: 'tech_english', text: '¿Cuál es tu nivel de inglés?', type: 'single', options: ['Básico', 'Intermedio', 'Avanzado', 'Nativo / Bilingüe'], field: 'languages' },
      { id: 'tech_certs', text: '¿Qué certificaciones profesionales tienes?', type: 'multiple', options: ['AWS Certified', 'Azure Certified', 'Google Cloud Certified', 'CISSP', 'CompTIA Security+', 'PMP', 'Scrum Master / CSM', 'Kubernetes (CKA/CKAD)', 'Oracle Certified', 'ITIL', 'Ninguna', 'Otra'], field: 'certifications' },
      { id: 'tech_summary', text: 'Describe tu experiencia en 2-3 líneas', type: 'text', field: 'summary' },
    ],
  },
  {
    id: 'salud',
    name: 'Salud / Medicina',
    description: 'Medicina, enfermería, ciencias de la salud',
    icon: '🏥',
    questions: [
      { id: 'health_specialty', text: '¿Cuál es tu especialidad o área?', type: 'single', options: ['Medicina General', 'Enfermería', 'Pediatría', 'Cardiología', 'Neurología', 'Odontología', 'Psicología', 'Fisioterapia', 'Nutrición', 'Farmacia', 'Veterinaria', 'Laboratorio / Imagenología', 'Salud Pública', 'Administración de Salud', 'Otro'], field: 'title' },
      { id: 'health_years', text: '¿Cuántos años de experiencia tienes?', type: 'single', options: ['0 años / Sin experiencia', 'Menos de 1 año', '1-3 años', '4-7 años', '8-15 años', 'Más de 15 años'], field: 'experience' },
      { id: 'health_education', text: '¿Cuál es tu nivel de educación?', type: 'single', options: ['Técnico', 'Pregrado', 'Especialización', 'Maestría', 'Doctorado'], field: 'education' },
      { id: 'health_certs', text: '¿Qué certificaciones o licencias adicionales tienes?', type: 'multiple', options: ['ACLS', 'BLS', 'PALS', 'ATLS', 'NRP', 'Certificacion de Especialidad Medica', 'Licencia de Enfermeria', 'RCP / DEA', 'Ninguna', 'Otra'], field: 'certifications',
        roleFilter: {
          'Medicina General': ['ACLS', 'BLS', 'PALS', 'ATLS', 'NRP', 'RCP / DEA', 'Certificacion de Especialidad Medica'],
          'Enfermería': ['ACLS', 'BLS', 'PALS', 'NRP', 'RCP / DEA', 'Licencia de Enfermeria'],
          'Pediatría': ['ACLS', 'BLS', 'PALS', 'NRP', 'RCP / DEA', 'Certificacion de Especialidad Medica'],
          'Cardiología': ['ACLS', 'BLS', 'Certificacion de Especialidad Medica'],
          'Neurología': ['ACLS', 'BLS', 'Certificacion de Especialidad Medica'],
          'Odontología': ['RCP / DEA'],
          'Psicología': ['RCP / DEA'],
          'Fisioterapia': ['ACLS', 'BLS', 'RCP / DEA'],
          'Nutrición': ['RCP / DEA'],
          'Farmacia': ['BLS', 'RCP / DEA'],
          'Veterinaria': ['RCP / DEA'],
          'Laboratorio / Imagenología': ['BLS', 'RCP / DEA'],
          'Salud Pública': ['BLS', 'RCP / DEA'],
          'Administración de Salud': ['RCP / DEA'],
          'Otro': ['ACLS', 'BLS', 'PALS', 'ATLS', 'NRP', 'Certificacion de Especialidad Medica', 'Licencia de Enfermeria', 'RCP / DEA', 'Ninguna', 'Otra'],
        },
      },
      { id: 'health_english', text: '¿Cuál es tu nivel de inglés?', type: 'single', options: ['Básico', 'Intermedio', 'Avanzado', 'Nativo / Bilingüe'], field: 'languages' },
      { id: 'health_summary', text: 'Describe tu experiencia en 2-3 líneas', type: 'text', field: 'summary' },
    ],
  },
  {
    id: 'finanzas',
    name: 'Finanzas / Contabilidad',
    description: 'Banca, contabilidad, auditoría, inversiones',
    icon: '📊',
    questions: [
      { id: 'fin_role', text: '¿Cuál es tu rol principal?', type: 'single', options: ['Contador', 'Auditor', 'Analista Financiero', 'Asesor de Inversiones', 'Controller', 'CFO / Director Financiero', 'Banquero', 'Agente de Seguros', 'Tesorería', 'Cumplimiento / AML', 'Otro'], field: 'title' },
      { id: 'fin_years', text: '¿Cuántos años de experiencia tienes?', type: 'single', options: ['0 años / Sin experiencia', 'Menos de 1 año', '1-3 años', '4-7 años', '8-15 años', 'Más de 15 años'], field: 'experience' },
      { id: 'fin_certs', text: '¿Qué certificaciones tienes?', type: 'multiple', options: ['CPA', 'CFA', 'CMA', 'CIA', 'FRM', 'CISA', 'Ninguna aún', 'Otra'], field: 'certifications' },
      { id: 'fin_tools', text: '¿Qué herramientas/software manejas?', type: 'multiple', options: ['Excel Avanzado', 'SAP', 'Oracle Financial', 'QuickBooks', 'Power BI', 'Tableau', 'Bloomberg', 'Python / R', 'SQL', 'Otro'], field: 'skills',
        roleFilter: {
          'Contador': ['Excel Avanzado', 'SAP', 'Oracle Financial', 'QuickBooks', 'Power BI', 'SQL'],
          'Auditor': ['Excel Avanzado', 'SAP', 'Oracle Financial', 'Power BI', 'Tableau', 'SQL'],
          'Analista Financiero': ['Excel Avanzado', 'Power BI', 'Tableau', 'Bloomberg', 'Python / R', 'SQL'],
          'Asesor de Inversiones': ['Excel Avanzado', 'Power BI', 'Bloomberg'],
          'Controller': ['Excel Avanzado', 'SAP', 'Oracle Financial', 'Power BI', 'SQL'],
          'CFO / Director Financiero': ['Excel Avanzado', 'SAP', 'Power BI'],
          'Banquero': ['Excel Avanzado', 'Power BI', 'Bloomberg', 'SQL'],
          'Agente de Seguros': ['Excel Avanzado', 'QuickBooks', 'Power BI'],
          'Tesorería': ['Excel Avanzado', 'SAP', 'Oracle Financial', 'Power BI', 'SQL'],
          'Cumplimiento / AML': ['Excel Avanzado', 'Power BI', 'Tableau', 'SQL'],
          'Otro': ['Excel Avanzado', 'SAP', 'Oracle Financial', 'QuickBooks', 'Power BI', 'Tableau', 'Bloomberg', 'Python / R', 'SQL', 'Otro'],
        },
      },
      { id: 'fin_education', text: '¿Cuál es tu nivel de educación?', type: 'single', options: ['Técnico', 'Pregrado', 'Postgrado / Maestría', 'MBA', 'Doctorado'], field: 'education' },
      { id: 'fin_english', text: '¿Cuál es tu nivel de inglés?', type: 'single', options: ['Básico', 'Intermedio', 'Avanzado', 'Nativo / Bilingüe'], field: 'languages' },
      { id: 'fin_summary', text: 'Describe tu experiencia en 2-3 líneas', type: 'text', field: 'summary' },
    ],
  },
  {
    id: 'educacion',
    name: 'Educación / Docencia',
    description: 'Docencia, investigación, administración educativa',
    icon: '📚',
    questions: [
      { id: 'edu_level', text: '¿En qué nivel educativo te desempeñas?', type: 'single', options: ['Educación Inicial / Preescolar', 'Educación Primaria', 'Educación Secundaria', 'Universidad / Pregrado', 'Postgrado / Maestría', 'Investigación', 'Educación Técnica', 'Administración Educativa', 'Otro'], field: 'title' },
      { id: 'edu_subjects', text: '¿Qué materias o áreas impartes?', type: 'multiple', options: ['Matemáticas', 'Ciencias', 'Lenguaje / Literatura', 'Historia / Sociales', 'Idiomas', 'Arte / Música', 'Tecnología / Informática', 'Educación Física', 'Filosofía / Ética', 'Ciencias Económicas', 'Otro'], field: 'skills' },
      { id: 'edu_years', text: '¿Cuántos años de experiencia docente tienes?', type: 'single', options: ['0 años / Sin experiencia', 'Menos de 1 año', '1-3 años', '4-7 años', '8-15 años', 'Más de 15 años'], field: 'experience' },
      { id: 'edu_education', text: '¿Cuál es tu nivel educativo máximo?', type: 'single', options: ['Pregrado', 'Especialización', 'Maestría', 'Doctorado', 'Postdoctorado'], field: 'education' },
      { id: 'edu_certs', text: '¿Qué certificaciones pedagógicas tienes?', type: 'multiple', options: ['Diplomado en Pedagogia', 'Certificacion en TIC Educativas', 'TOEFL / IELTS', 'Certificacion en Diseno Curricular', 'Diplomado en Educacion Inclusiva', 'Certificacion en Evaluacion Educativa', 'Ninguna', 'Otra'], field: 'certifications' },
      { id: 'edu_english', text: '¿Cuál es tu nivel de inglés?', type: 'single', options: ['Básico', 'Intermedio', 'Avanzado', 'Nativo / Bilingüe'], field: 'languages' },
      { id: 'edu_summary', text: 'Describe tu experiencia en 2-3 líneas', type: 'text', field: 'summary' },
    ],
  },
  {
    id: 'ventas',
    name: 'Ventas / Marketing',
    description: 'Ventas, marketing digital, publicidad, relaciones públicas',
    icon: '📈',
    questions: [
      { id: 'ventas_role', text: '¿Cuál es tu rol principal?', type: 'single', options: ['Ejecutivo de Ventas', 'Account Manager', 'Marketing Digital', 'Content Manager / Copywriter', 'Social Media Manager', 'SEO / SEM', 'Brand Manager', 'Trade Marketing', 'Ventas Técnicas', 'Business Development', 'E-commerce', 'Otro'], field: 'title' },
      { id: 'ventas_years', text: '¿Cuántos años de experiencia tienes?', type: 'single', options: ['0 años / Sin experiencia', 'Menos de 1 año', '1-3 años', '4-7 años', '8-15 años', 'Más de 15 años'], field: 'experience' },
      { id: 'ventas_tools', text: '¿Qué herramientas/platformas manejas?', type: 'multiple', options: ['Salesforce', 'HubSpot', 'Google Ads', 'Meta Ads', 'Google Analytics', 'SEMrush', 'Mailchimp', 'WordPress', 'Shopify', 'Canva', 'Photoshop / Illustrator', 'Otro'], field: 'skills',
        roleFilter: {
          'Ejecutivo de Ventas': ['Salesforce', 'HubSpot', 'Mailchimp'],
          'Account Manager': ['Salesforce', 'HubSpot', 'Mailchimp'],
          'Marketing Digital': ['Google Ads', 'Meta Ads', 'Google Analytics', 'SEMrush', 'Mailchimp', 'Canva'],
          'Content Manager / Copywriter': ['WordPress', 'Canva', 'Google Analytics', 'Mailchimp', 'Photoshop / Illustrator'],
          'Social Media Manager': ['Meta Ads', 'Google Ads', 'Canva', 'Google Analytics', 'Photoshop / Illustrator'],
          'SEO / SEM': ['Google Ads', 'Google Analytics', 'SEMrush', 'WordPress'],
          'Brand Manager': ['Canva', 'Photoshop / Illustrator', 'Google Analytics', 'Meta Ads'],
          'Trade Marketing': ['Google Analytics', 'Canva', 'Photoshop / Illustrator'],
          'Ventas Técnicas': ['Salesforce', 'HubSpot', 'Google Analytics'],
          'Business Development': ['Salesforce', 'HubSpot', 'Google Analytics', 'Mailchimp'],
          'E-commerce': ['Shopify', 'Google Analytics', 'Google Ads', 'Meta Ads', 'Mailchimp', 'Canva', 'WordPress'],
          'Otro': ['Salesforce', 'HubSpot', 'Google Ads', 'Meta Ads', 'Google Analytics', 'SEMrush', 'Mailchimp', 'WordPress', 'Shopify', 'Canva', 'Photoshop / Illustrator', 'Otro'],
        },
      },
      { id: 'ventas_education', text: '¿Cuál es tu nivel de educación?', type: 'single', options: ['Técnico', 'Pregrado', 'Postgrado / Maestría', 'MBA'], field: 'education' },
      { id: 'ventas_english', text: '¿Cuál es tu nivel de inglés?', type: 'single', options: ['Básico', 'Intermedio', 'Avanzado', 'Nativo / Bilingüe'], field: 'languages' },
      { id: 'ventas_summary', text: 'Describe tu experiencia en 2-3 líneas', type: 'text', field: 'summary' },
    ],
  },
  {
    id: 'ingenieria',
    name: 'Ingeniería (No IT)',
    description: 'Ingeniería civil, mecánica, eléctrica, industrial',
    icon: '⚙️',
    questions: [
      { id: 'ing_branch', text: '¿Cuál es tu rama de ingeniería?', type: 'single', options: ['Civil', 'Mecánica', 'Eléctrica', 'Electrónica', 'Industrial', 'Química', 'Ambiental', 'Minas / Metalúrgica', 'Petróleos / Gas', 'Biomédica', 'Alimentos', 'Otra'], field: 'title' },
      { id: 'ing_years', text: '¿Cuántos años de experiencia tienes?', type: 'single', options: ['0 años / Sin experiencia', 'Menos de 1 año', '1-3 años', '4-7 años', '8-15 años', 'Más de 15 años'], field: 'experience' },
      { id: 'ing_software', text: '¿Qué software o herramientas técnicas manejas?', type: 'multiple', options: ['AutoCAD', 'SolidWorks', 'Revit', 'MATLAB', 'ETABS', 'SAP2000', 'Primavera / MS Project', 'PLC / SCADA', 'LabVIEW', 'ANSYS', 'ArcGIS', 'Python / R', 'Otro'], field: 'skills',
        roleFilter: {
          'Civil': ['AutoCAD', 'Revit', 'ETABS', 'SAP2000', 'Primavera / MS Project', 'ArcGIS'],
          'Mecánica': ['AutoCAD', 'SolidWorks', 'MATLAB', 'ANSYS', 'PLC / SCADA'],
          'Eléctrica': ['AutoCAD', 'MATLAB', 'PLC / SCADA', 'LabVIEW'],
          'Electrónica': ['MATLAB', 'LabVIEW', 'PLC / SCADA', 'Python / R'],
          'Industrial': ['AutoCAD', 'Primavera / MS Project', 'Python / R'],
          'Química': ['MATLAB', 'PLC / SCADA', 'Python / R'],
          'Ambiental': ['AutoCAD', 'ArcGIS', 'MATLAB', 'Python / R'],
          'Minas / Metalúrgica': ['AutoCAD', 'SolidWorks', 'ArcGIS', 'MATLAB'],
          'Petróleos / Gas': ['AutoCAD', 'MATLAB', 'PLC / SCADA', 'Primavera / MS Project'],
          'Biomédica': ['MATLAB', 'LabVIEW', 'SolidWorks', 'Python / R'],
          'Alimentos': ['MATLAB', 'PLC / SCADA', 'Python / R'],
          'Otra': ['AutoCAD', 'SolidWorks', 'Revit', 'MATLAB', 'ETABS', 'SAP2000', 'Primavera / MS Project', 'PLC / SCADA', 'LabVIEW', 'ANSYS', 'ArcGIS', 'Python / R', 'Otro'],
        },
      },
      { id: 'ing_certs', text: '¿Qué certificaciones profesionales tienes?', type: 'multiple', options: ['PE License', 'PMP', 'LEED', 'Six Sigma Green Belt', 'Six Sigma Black Belt', 'OSHA', 'Certificacion en BIM', 'Ninguna', 'Otra'], field: 'certifications' },
      { id: 'ing_education', text: '¿Cuál es tu nivel de educación?', type: 'single', options: ['Técnico', 'Pregrado', 'Especialización', 'Maestría', 'Doctorado'], field: 'education' },
      { id: 'ing_english', text: '¿Cuál es tu nivel de inglés?', type: 'single', options: ['Básico', 'Intermedio', 'Avanzado', 'Nativo / Bilingüe'], field: 'languages' },
      { id: 'ing_summary', text: 'Describe tu experiencia en 2-3 líneas', type: 'text', field: 'summary' },
    ],
  },
  {
    id: 'legal',
    name: 'Legal / Jurídico',
    description: 'Derecho, asesoría jurídica, cumplimiento normativo',
    icon: '⚖️',
    questions: [
      { id: 'legal_area', text: '¿Cuál es tu área de práctica?', type: 'single', options: ['Derecho Corporativo', 'Derecho Laboral', 'Derecho Tributario', 'Derecho Civil', 'Derecho Penal', 'Derecho Constitucional', 'Propiedad Intelectual', 'Cumplimiento / Compliance', 'Derecho Digital / Tech', 'Litigio', 'Notaría / Registro', 'Otro'], field: 'title' },
      { id: 'legal_years', text: '¿Cuántos años de experiencia tienes?', type: 'single', options: ['0 años / Sin experiencia', 'Menos de 1 año', '1-3 años', '4-7 años', '8-15 años', 'Más de 15 años'], field: 'experience' },
      { id: 'legal_bar', text: '¿En qué colegios de abogados o barras estás admitido?', type: 'multiple', options: ['Colegio de Abogados (local)', 'Barra de EE.UU. — Estado (especificar)', 'ICADE / ICAM', 'Barra de la Abogacia (Espania)', 'Colegio de Abogados (Mexico)', 'Otra', 'Ninguna'], field: 'certifications' },
      { id: 'legal_education', text: '¿Cuál es tu nivel de educación?', type: 'single', options: ['Pregrado', 'Especialización', 'Maestría (LL.M.)', 'Doctorado'], field: 'education' },
      { id: 'legal_english', text: '¿Cuál es tu nivel de inglés?', type: 'single', options: ['Básico', 'Intermedio', 'Avanzado', 'Nativo / Bilingüe'], field: 'languages' },
      { id: 'legal_summary', text: 'Describe tu experiencia en 2-3 líneas', type: 'text', field: 'summary' },
    ],
  },
  {
    id: 'admin',
    name: 'Administrativo / Oficina',
    description: 'Asistencia, recursos humanos, administración general',
    icon: '📋',
    questions: [
      { id: 'admin_role', text: '¿Cuál es tu rol principal?', type: 'single', options: ['Asistente Administrativo', 'Recepcionista', 'Secretario/a', 'Auxiliar de RRHH', 'Analista de RRHH', 'Asistente de Gerencia', 'Administrador de Oficina', 'Coordinador Administrativo', 'Auxiliar Contable', 'Facturación / Cobranzas', 'Servicio al Cliente', 'Otro'], field: 'title' },
      { id: 'admin_years', text: '¿Cuántos años de experiencia tienes?', type: 'single', options: ['0 años / Sin experiencia', 'Menos de 1 año', '1-3 años', '4-7 años', '8-15 años', 'Más de 15 años'], field: 'experience' },
      { id: 'admin_software', text: '¿Qué software manejas?', type: 'multiple', options: ['Microsoft Office', 'Excel Avanzado', 'Google Workspace', 'SAP', 'QuickBooks', 'Salesforce', 'Slack', 'Trello / Asana', 'Power BI', 'Otro'], field: 'skills' },
      { id: 'admin_education', text: '¿Cuál es tu nivel de educación?', type: 'single', options: ['Secundaria', 'Técnico', 'Pregrado', 'Postgrado'], field: 'education' },
      { id: 'admin_english', text: '¿Cuál es tu nivel de inglés?', type: 'single', options: ['Básico', 'Intermedio', 'Avanzado', 'Nativo / Bilingüe'], field: 'languages' },
      { id: 'admin_summary', text: 'Describe tu experiencia en 2-3 líneas', type: 'text', field: 'summary' },
    ],
  },
  {
    id: 'arte',
    name: 'Arte / Diseño',
    description: 'Diseño gráfico, ilustración, animación, arquitectura',
    icon: '🎨',
    questions: [
      { id: 'arte_discipline', text: '¿Cuál es tu disciplina principal?', type: 'single', options: ['Diseño Gráfico', 'Diseño UX / UI', 'Ilustrador/a', 'Animador/a', 'Diseñador Industrial', 'Arquitecto/a', 'Fotógrafo/a', 'Diseñador de Interiores', 'Motion Graphics', 'Diseñador de Modas', 'Artista Plástico', 'Otro'], field: 'title' },
      { id: 'arte_years', text: '¿Cuántos años de experiencia tienes?', type: 'single', options: ['0 años / Sin experiencia', 'Menos de 1 año', '1-3 años', '4-7 años', '8-15 años', 'Más de 15 años'], field: 'experience' },
      { id: 'arte_tools', text: '¿Qué herramientas/software usas?', type: 'multiple', options: ['Adobe Photoshop', 'Adobe Illustrator', 'Figma', 'Sketch', 'Blender', 'Maya', 'After Effects', 'Premiere Pro', 'AutoCAD', 'Procreate', 'InDesign', 'Lightroom', 'Otro'], field: 'skills',
        roleFilter: {
          'Diseño Gráfico': ['Adobe Photoshop', 'Adobe Illustrator', 'Figma', 'InDesign', 'Procreate'],
          'Diseño UX / UI': ['Figma', 'Sketch', 'Adobe Illustrator', 'Adobe Photoshop', 'After Effects'],
          'Ilustrador/a': ['Adobe Illustrator', 'Procreate', 'Adobe Photoshop', 'Blender'],
          'Animador/a': ['Blender', 'Maya', 'After Effects', 'Adobe Photoshop'],
          'Diseñador Industrial': ['AutoCAD', 'Blender', 'Adobe Illustrator'],
          'Arquitecto/a': ['AutoCAD', 'Sketch', 'Blender', 'Adobe Photoshop'],
          'Fotógrafo/a': ['Adobe Photoshop', 'Lightroom', 'Premiere Pro'],
          'Diseñador de Interiores': ['AutoCAD', 'Sketch', 'Adobe Photoshop', 'Blender'],
          'Motion Graphics': ['After Effects', 'Premiere Pro', 'Adobe Illustrator', 'Adobe Photoshop', 'Blender'],
          'Diseñador de Modas': ['Adobe Illustrator', 'Adobe Photoshop', 'Procreate'],
          'Artista Plástico': ['Adobe Photoshop', 'Adobe Illustrator', 'Procreate', 'Blender'],
          'Otro': ['Adobe Photoshop', 'Adobe Illustrator', 'Figma', 'Sketch', 'Blender', 'Maya', 'After Effects', 'Premiere Pro', 'AutoCAD', 'Procreate', 'InDesign', 'Lightroom', 'Otro'],
        },
      },
      { id: 'arte_education', text: '¿Cuál es tu nivel de educación?', type: 'single', options: ['Técnico', 'Pregrado', 'Postgrado / Maestría'], field: 'education' },
      { id: 'arte_english', text: '¿Cuál es tu nivel de inglés?', type: 'single', options: ['Básico', 'Intermedio', 'Avanzado', 'Nativo / Bilingüe'], field: 'languages' },
      { id: 'arte_summary', text: 'Describe tu experiencia en 2-3 líneas', type: 'text', field: 'summary' },
    ],
  },
]

export const questions: Question[] = [
  { id: 'name', text: '¿Cuál es tu nombre completo?', type: 'text', field: 'name' },
  { id: 'email', text: '¿Cuál es tu correo electrónico?', type: 'text', field: 'email' },
  { id: 'phone', text: '¿Cuál es tu teléfono de contacto?', type: 'text', field: 'phone' },
  { id: 'location', text: '¿En qué ciudad/país te encuentras?', type: 'text', field: 'location' },
  { id: 'target_market', text: '¿En qué país o mercado laboral quieres insertarte?', type: 'single', options: ['República Dominicana', 'México', 'Colombia', 'Argentina', 'Chile', 'Perú', 'España', 'Estados Unidos', 'Europa (otro)', 'Latinoamérica (otro)', 'Remoto (internacional)', 'Otro'], field: 'targetMarket' },
  { id: 'github', text: '¿Cuál es la URL de tu perfil de GitHub?', type: 'text', field: 'github' },
  { id: 'linkedin', text: '¿Cuál es la URL de tu perfil de LinkedIn?', type: 'text', field: 'linkedin' },
  { id: 'portfolio', text: '¿Cuál es la URL de tu portafolio o sitio web personal?', type: 'text', field: 'portfolio' },
  { id: 'education_institution', text: '¿Cuál es tu institución educativa?', type: 'text', field: 'education_institution' },
  { id: 'education_field', text: '¿Cuál es tu campo de estudio?', type: 'text', field: 'education_field' },
  { id: 'education_start', text: '¿Año de inicio?', type: 'text', field: 'education_start' },
  { id: 'education_end', text: '¿Año de graduación?', type: 'text', field: 'education_end' },
]
